from __future__ import annotations

import unittest
from pathlib import Path


class FrontendModuleSplitTests(unittest.TestCase):
    def test_index_loads_api_and_formatter_modules_before_app(self) -> None:
        html = Path("github_release_watcher/static/index.html").read_text(encoding="utf-8")
        api_pos = html.find('src="/api-client.js"')
        fmt_pos = html.find('src="/formatters.js"')
        logs_pos = html.find('src="/logs-view.js"')
        repos_pos = html.find('src="/repos-controller.js"')
        settings_pos = html.find('src="/settings-controller.js"')
        storage_diag_pos = html.find('src="/storage-diagnostics.js"')
        batch_selectors_pos = html.find('src="/batch-selectors.js"')
        batch_actions_pos = html.find('src="/batch-actions.js"')
        mobile_behavior_pos = html.find('src="/mobile-behavior.js"')
        app_ui_utils_pos = html.find('src="/app-ui-utils.js"')
        app_auth_pos = html.find('src="/app-auth.js"')
        app_settings_dialog_pos = html.find('src="/app-settings-dialog.js"')
        app_events_pos = html.find('src="/app-events.js"')
        app_runtime_pos = html.find('src="/app-runtime.js"')
        app_pos = html.find('src="/app.js"')
        self.assertGreaterEqual(api_pos, 0)
        self.assertGreaterEqual(fmt_pos, 0)
        self.assertGreaterEqual(logs_pos, 0)
        self.assertGreaterEqual(repos_pos, 0)
        self.assertGreaterEqual(settings_pos, 0)
        self.assertGreaterEqual(storage_diag_pos, 0)
        self.assertGreaterEqual(batch_selectors_pos, 0)
        self.assertGreaterEqual(batch_actions_pos, 0)
        self.assertGreaterEqual(mobile_behavior_pos, 0)
        self.assertGreaterEqual(app_ui_utils_pos, 0)
        self.assertGreaterEqual(app_auth_pos, 0)
        self.assertGreaterEqual(app_settings_dialog_pos, 0)
        self.assertGreaterEqual(app_events_pos, 0)
        self.assertGreaterEqual(app_runtime_pos, 0)
        self.assertGreaterEqual(app_pos, 0)
        self.assertLess(api_pos, app_pos)
        self.assertLess(fmt_pos, app_pos)
        self.assertLess(logs_pos, app_pos)
        self.assertLess(repos_pos, app_pos)
        self.assertLess(settings_pos, app_pos)
        self.assertLess(storage_diag_pos, app_pos)
        self.assertLess(batch_selectors_pos, app_pos)
        self.assertLess(batch_actions_pos, app_pos)
        self.assertLess(mobile_behavior_pos, app_pos)
        self.assertLess(app_ui_utils_pos, app_pos)
        self.assertLess(app_auth_pos, app_pos)
        self.assertLess(app_settings_dialog_pos, app_pos)
        self.assertLess(app_events_pos, app_pos)
        self.assertLess(app_ui_utils_pos, app_runtime_pos)
        self.assertLess(app_auth_pos, app_runtime_pos)
        self.assertLess(app_settings_dialog_pos, app_runtime_pos)
        self.assertLess(app_events_pos, app_runtime_pos)
        self.assertLess(app_runtime_pos, app_pos)

    def test_app_bootstrap_uses_shared_global_modules(self) -> None:
        app_js = Path("github_release_watcher/static/app.js").read_text(encoding="utf-8")
        self.assertIn("window.GRWApiClient", app_js)
        self.assertIn("window.GRWFormatters", app_js)
        self.assertIn("window.GRWLogsView", app_js)
        self.assertIn("window.GRWRepoController", app_js)
        self.assertIn("window.GRWSettingsController", app_js)
        self.assertIn("window.GRWStorageDiagnostics", app_js)
        self.assertIn("window.GRWBatchSelectors", app_js)
        self.assertIn("window.GRWBatchActions", app_js)
        self.assertIn("window.GRWMobileBehavior", app_js)
        self.assertIn("window.GRWAppRuntime", app_js)
        self.assertNotIn("const API = {", app_js)
        self.assertNotIn("function renderStructuredLogs(", app_js)

    def test_app_runtime_uses_auth_and_ui_modules(self) -> None:
        runtime_js = Path("github_release_watcher/static/app-runtime.js").read_text(encoding="utf-8")
        self.assertIn("window.GRWAppUiUtils", runtime_js)
        self.assertIn("window.GRWAppAuth", runtime_js)
        self.assertIn("window.GRWAppSettingsDialog", runtime_js)
        self.assertIn("window.GRWAppEvents", runtime_js)
        self.assertNotIn("function startLoginFlow(", runtime_js)
        self.assertNotIn("async function requireLogin(", runtime_js)
        self.assertNotIn("function toast(", runtime_js)
        self.assertNotIn("function setButtonBusy(", runtime_js)
        self.assertNotIn("function wireEvents(", runtime_js)
        self.assertNotIn("function syncSettingsFormFromDraft(", runtime_js)
        self.assertNotIn("function syncDraftFromSettingsForm(", runtime_js)


if __name__ == "__main__":
    unittest.main()
